### PR TITLE
task5

### PR DESCRIPTION
**Pull request by Dmytr0n**

### CODE REVIEW

**Comment by andrii-s-spitzer-lpnu-ua** [comment]
remove bin and autogenerated files

**Comment by Dmytr0n** [comment]
> remove bin and autogenerated files

removed bin and autogeneration files

**Comment by Dmytr0n** [comment]
> remove bin and autogenerated files

removed folder Tools

**Comment by Dmytr0n** [comment]
> remove bin and autogenerated files

removed folder Tools

**Comment by andrii-s-spitzer-lpnu-ua** [comment]
plesease remove bin folder as well

**Review by andrii-s-spitzer-lpnu-ua — APPROVED** [review]

**Pull request merged**
